### ISSUE TITLE
Align depth to color frame

### ISSUE THREAD

**Issue by zc-alexfan** [guiggh/hand_pose_action#10]
Very impressive work! Thanks for sharing your dataset and providing a detailed codebase for us to start with. I am interested in an application that requires alignment of the color and depth images but it seems that they are shot in different coordinate frames. I am wondering if there is a way to map depth images to the color image frame?

I tried looking into the realsense github page, but the depth2image interface for that library is only for either bag files (raw realsense data file) or streaming data. It would be nice if you could point me to either a code base or something else.

I am unfamiliar with camera transform. I don't know if it is possible to do the mapping using the camera parameters you provided? Thanks!

**Comment by guiggh** [comment]
Yes, it's possible. Please have a look at the python script and the camera parameters provided.
