### ISSUE TITLE
Could not download dataset properly. 

### ISSUE THREAD

**Issue by anl13** [guiggh/hand_pose_action#11]
I tried to download the dataset after filling the form, however, I come up with two problems: 
1. When I tried to download all files into a single zip, it says file too large to download. 
2. When I tried to download the video of a single subject, it always breaks after downloading about half of the data. (not network linking problem, just could not download file, and it says `Fail, can not find the file`. 

Does anyone have the same problem?

**Comment by anl13** [comment]
I use MicroSoft Edge instead of Chrome to download the data, and it is ok.

**Comment by lvZic** [comment]
> I use MicroSoft Edge instead of Chrome to download the data, and it is ok.

I still can't download the whole file, either on chrome or edge.
