### ISSUE TITLE
False alignment when project 3D hand skeleton and object to 2D image plane

### ISSUE THREAD

**Issue by fylwen** [guiggh/hand_pose_action#13]
Hi. I've tried both load_example.m and load_example.py, however, I consider that for some sequences, the alignment from the skeleton and object_pose to image is problematic and does not globally match. I list some screenshots of frame examples below, which are generated by load_example.py; I also checked with the load_example.m, and the same issue exists:

Subject2 pour_milk sequence1 frame119
![Subject2_pour_milk_sequence1_frame119](https://user-images.githubusercontent.com/48756873/114160458-85270c80-9959-11eb-951b-c5fdc15ef872.png)

Subject3 pour milk sequence3 frame41
![Subject3_pour_milk_sequence3_frame41](https://user-images.githubusercontent.com/48756873/114160917-0383ae80-995a-11eb-8508-36d5dabaa10b.png)

Subject6 pour milk sequence1 frame45
![Subject6_pour_milk_sequence1_frame45](https://user-images.githubusercontent.com/48756873/114160904-fff02780-9959-11eb-862d-96af15f2e363.png)

Subject4 read letter sequence3 frame88
![Subject4_read_letter_sequence3_frame88](https://user-images.githubusercontent.com/48756873/114160884-fb2b7380-9959-11eb-80f6-90066c358636.png)

Subject4 read letter sequence3 frame188
![Subject4_read_letter_sequence3_frame188](https://user-images.githubusercontent.com/48756873/114160694-c8817b00-9959-11eb-97ca-1ca88021fc7d.png)

It seems that something related to the camera parameter goes wrong, and I here open the issue to seek help.

Furthermore, it seems that for Subject 5 open/close/pour liquid soap, I cannot find the object pose label for Sequence 1~4.

Many thanks for the valuable help!

Best regards,
Frances

**Comment by guiggh** [comment]
This is a known issue on some of the annotated sequences due to some bad calibration. I'm afraid this will stay like this as it's hard to fix without manually extensive work.
