### ISSUE TITLE
How could i use 'data_split_action_recognition.txt'

### ISSUE THREAD

**Issue by tungts1101** [guiggh/hand_pose_action#16]
I found a comment on README.txt that the train-test ratio is based on this file, but how could I use it for splitting the train and test sets? Is each line on this file according to one image in the train set?

**Comment by guiggh** [comment]
They point to sequences, not images. So each folder of images are a sequence of a particular class following the split on the file. Hope it helps.

**Comment by Hamzac070** [comment]
The file contains subject, action_name, and action_id but what is the 3rd column? 
Subject_1/use_flash/3 24
Subject_1/write/1 25
Subject_1/write/3 25
Subject_1/tear_paper/1 26
Subject_1/tear_paper/3 26
