### ISSUE TITLE
Normalized action sequences

### ISSUE THREAD

**Issue by algvr** [guiggh/hand_pose_action#17]
Dear authors, thanks for your amazing work!

Would it be possible to provide a mapping from the indices in "action_sequences_normalized" to the corresponding action sequences? This would make it possible to use the image data of the sequences as well when training methods on your dataset.

Also, do you recall the coordinate system scale used for these normalized action sequences? I assume that for the unnormalized version, it's millimeters, but I can't find a good unit for the normalized ones. Meters don't seem to make much sense based on the coordinate ranges. Here's an example of a frame's normalized joint positions. Every 3rd coordinate corresponds to the same dimension, and dimension 2 (counting from 0) has a range of at least [0, 0.6] (check the 3rd and last element of the array), which does not correspond to a human hand's scale measured in meters.

![image](https://github.com/guiggh/hand_pose_action/assets/88772339/45920007-f170-42d6-aa16-80c581876c3c)

Thank you very much in advance!

**Comment by guiggh** [comment]
Hello, thanks for the interest in this project!

> Would it be possible to provide a mapping from the indices in "action_sequences_normalized" to the corresponding action sequences? This would make it possible to use the image data of the sequences as well when training methods on your dataset.

- They should be in the same order as in `data_split_action_recognition.txt`. To use it with images in different ways you can always normalize them yourself.

>  I assume that for the unnormalized version, it's millimeters, but I can't find a good unit for the normalized ones.

The normalized units don't have any physical meaning.
