### ISSUE TITLE
Link of data and pretrained model download

### ISSUE THREAD

**Issue by momo1986** [guiggh/hand_pose_action#3]
Hello, is there any link of data and pretriend model which can be downloaded.

**Comment by guiggh** [comment]
You can request access to the data filling [this form](https://goo.gl/forms/FIsXpYVIUov0j7Wv2).

**Comment by m3m3-chan** [comment]
Hello, 

Is the pretrained model shared too?
thanks,

**Comment by guiggh** [comment]
Not at this time. You can request access to everything available [here](https://docs.google.com/forms/d/e/1FAIpQLScoksYrmthDbJeAV0_ysXJDmfvZmzMMsX0_Uhkb6H6DHYGBtg/viewform)
