### ISSUE TITLE
Precomputed centers from deep prior++

### ISSUE THREAD

**Issue by chaiban** [guiggh/hand_pose_action#6]
Hi @guiggh ,

I am try to implement V2V PoseNet using your dataset. It requires centers for the dataset.

By any chance did you compute centers for Action dataset using deep prior++?

If please forward to my mail: bandi.chai414@gmail.com

Thanks!

**Comment by guiggh** [comment]
Centers can be computed using the provided hand pose annotations. You can also access precomputed bounding boxes available for the [HANDS 2019 challenge].(https://sites.google.com/view/hands2019/challenge)
