### ISSUE TITLE
Baseline LSTM for action recognition

### ISSUE THREAD

**Issue by yasserboutaleb** [guiggh/hand_pose_action#7]
Hello,

Will the codes of the baseline **LSTM for action recognition** be open-source?

Best regards,
Yasser BOUTALEB

**Comment by guiggh** [comment]
The implementation used on the paper experiment was a vanilla LSTM using tensorflow based on this  public [repo](https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/3_NeuralNetworks/dynamic_rnn.py). Don't forget to normalize the sequences (or download the already normalized ones from the dataset folder) if you are attempting to replicate the results on the paper!

**Comment by yasserboutaleb** [comment]
Thank you for your quick reply and for sharing. Yes I'm trying to replicate the results (the action recognition part).

**Comment by yasserboutaleb** [comment]
Hello again @guiggh, 

Please, I have one last question, did you have padded the sequences with zeros to a fixed max size ? Thank you in advance.

**Comment by guiggh** [comment]
Hi @Bestyasser, we used 120 frames as fixed max size and padded with zeros up to that number if the sequence is shorter. If the sequence is longer, we just cut the tail of the sequence and fill up to 120 frames. Hope it helps!
