### ISSUE TITLE
Can not access the dataset by website link :https://imperialcollegelondon.app.box.com/v/first-person-action-benchmark

### ISSUE THREAD

**Issue by kallianisawesome** [guiggh/hand_pose_action#9]
Sorry to interrupt, I can not access the fist-person-hand-action  dataset by your link:https://imperialcollegelondon.app.box.com/v/first-person-action-benchmark.
I have filled the form as required, but the website link just didn't work, can you fixed it? 
Thanks.

**Comment by guiggh** [comment]
There's nothing we can do about the host provider. Please try again.
